### ISSUE TITLE
Реализовать тест правильности последовательности вызовов событий формы

### ISSUE THREAD

**Issue by artbear** [ret-Phoenix/oscript-simple-gui#11]
Рекомендую использовать технику TDD "журнал" для фиксации последовательности вызовов событий.
Например, можно посмотреть https://github.com/artbear/1bdd/blob/develop/features/core/step_definitions/Hooks.os

**Comment by ret-Phoenix** [comment]
Правильно ли я понял: 
1. На каждый шаг создается отдельный тест.
2. Результат теста пишется в лог
3. После прохода всех шагов (тестов) идет сверка журнала логов и ожидаемого текста лога

**Comment by artbear** [comment]
нет, в одном тесте можно и нужно.
У меня еще для 77 и 1С++ был тест проверки правильности вызова спец.событий формы 1С++ и ФормЕкс.
Например, в коде ПриОткрытии и ПриЗакрытии ты добавляешь текст "ПриОткрытии" и "ПриЗакрытии" соответственно.
в коде теста ты создаешь журнал пустым, далее открываешь форму и закрываешь ее, далее читаешь журнал и проверяешь на равенство "ПриОткрытии;ПриЗакрытии;"
Профит.

**Comment by ret-Phoenix** [comment]
Ага, понял, близкое к этому сделало в https://github.com/ret-Phoenix/oscript-simple-gui/blob/master/tests/test-FormField-InputField.os#L214
