### ISSUE TITLE
Ошибка подключения внешней компоненты...

### ISSUE THREAD

**Issue by bbslipers** [ret-Phoenix/oscript-simple-gui#12]
ПодключитьВнешнююКомпоненту("oscript-simple-gui.dll");

Script started: 08.08.2016 10:32:11
{Модуль C:\1CScript\bin\test.os / Ошибка в строке: 1 / Внешнее исключение: Не удалось загрузить файл или сборку "file:///C:\1CScript\bin\oscript-simple-gui.dll" либо одну из их зависимостей. Операция не поддерживается. (Исключение из HRESULT: 0x80131515)}    
ПодключитьВнешнююКомпоненту("oscript-simple-gui.dll");

**Comment by ret-Phoenix** [comment]
Нужно проверить пути. Самый простой вариант: положить файл в каталог со скриптом.

**Comment by bbslipers** [comment]
Так в данный момент и есть :(

[Скриншот](http://joxi.ru/Vm6a51jCkxODrZ)

**Comment by ret-Phoenix** [comment]
выложить архивом каталог можете? у себя проверю.
Пока что не было проблем с подключением.

**Comment by bbslipers** [comment]
http://my-files.ru/lj37rp

**Comment by ret-Phoenix** [comment]
попробовал у себя - все видит. убирал свою сборку на компе, менял на Вашу.
Попробуйте явно указать путь к файлу. Мне кажется проблемы с путями и поиском файлов.

**Comment by ret-Phoenix** [comment]
ПодключитьВнешнююКомпоненту("oscript-simple-gui.dll");

SGUI = Новый ПростойГУИ();
Сообщить("Верия: " + SGUI.Версия);
---
Выводит как надо...

**Comment by bbslipers** [comment]
Help!!!
По Team Viewer получится подключится?

**Comment by ret-Phoenix** [comment]
AnyDesk - получится.

**Comment by bbslipers** [comment]
583458343

**Comment by ret-Phoenix** [comment]
+

**Comment by ret-Phoenix** [comment]
Контроль над управлением дайте

**Comment by ret-Phoenix** [comment]
Разобрались. Нужно было пересобрать проект под ОС. Буду разбираться с параметрами сборки проекта, чтобы можно было всегда просто копировать.

Спасибо за содействие.

**Comment by EvilBeaver** [comment]
Я проблему так и не понял. Я собираю 2013 студией и оно работает в линуксе и на винде. Просто копированием бинарников

**Comment by ret-Phoenix** [comment]
Собрал бинарник на Win 8.1 в VS 2015 Community - на машинах с WinServer при попытке загрузить этот бинарник: Внешнее исключение: Не удалось загрузить файл или сборку "file:///C:\1CScript\bin\oscript-simple-gui.dll" либо одну из их зависимостей

Если собираю бинарник в WinServer - тогда работает и на серверной ОС и на Win8.1

**Comment by ret-Phoenix** [comment]
хм. непонятно. скачал собранный из Master все запустилось.
До этого брал файл от bbslipers и он работал только на win 8.1, на серверной ОС не пошло

**Comment by EvilBeaver** [comment]
Скорее всего там был включен фреймворк не 4.0, а какой-то другой

**Comment by ret-Phoenix** [comment]
либо как-то странно сохранился файл...

**Comment by alehinsasha** [comment]
У меня такая же проблема, что и у темы issue. Как ее решить?

**Comment by ret-Phoenix** [comment]
Каким образом был получен файл? у меня подозрение на кривую скачку. т.к. у себя теперь собираю на Win 8, и спокойно запускаю на Win 8, 10, 2012

**Comment by alehinsasha** [comment]
@ret-Phoenix Склонировал репозиторий проекта, взял файл из каталога `\releases`. Вообще как с этим   файлом поступить правильнее? Может документацию расширить темой _"Как использовать"_?)

**Comment by ret-Phoenix** [comment]
А если попробовать скачать проект как zip файл, будет та же проблема с dll?

> Может документацию расширить темой "Как использовать"?)
чем не подходит:
- https://github.com/ret-Phoenix/oscript-simple-gui/tree/master/examples
- https://github.com/ret-Phoenix/oscript-simple-gui/tree/master/bin/src
- https://github.com/ret-Phoenix/oscript-simple-gui/tree/master/tests
- https://github.com/ret-Phoenix/oscript-simple-gui/blob/master/README.md (указаны все свойства и методы)
- http://infostart.ru/public/540284/

Т.о. примеров по работе с компонентой много. Не стоит забывать, что API практически идентичен 1С.

**Comment by alehinsasha** [comment]
@ret-Phoenix 
> Нужно проверить пути. Самый простой вариант: положить файл в каталог со скриптом.

т.к. видимо есть вариант - вопрос: _где должен лежать *.dll файл?_

**Comment by artbear** [comment]
@ret-Phoenix Включи инфу выше в офиц. документацию продукта, очень полезно для пользователей.

**Comment by ret-Phoenix** [comment]
Лежать - где угодно )

> ПодключитьВнешнююКомпоненту / AttachAddIn()
> Пример:
> 
> ПодключитьВнешнююКомпоненту("C:\MyAssembly.dll");
> КлассИзКомпоненты = Новый КлассИзКомпоненты(); // тип объявлен внутри компоненты
> ПодключитьВнешнююКомпоненту("C:\MyAssembly.dll"); КлассИзКомпоненты = Новый КлассИзКомпоненты(); // тип объявлен внутри компоненты
> 
> Подключает внешнюю сборку среды .NET (*.dll) и регистрирует классы 1Script, объявленные в этой сборке. Публичные классы, отмеченные в dll атрибутом ContextClass, будут импортированы аналогично встроенным классам 1Script. Загружаемая сборка должна ссылаться на сборку ScriptEngine.dll
> 
> Параметры
> 
> dllPath: Путь к внешней компоненте

Я предпочитаю класть в каталог с oscript, и загружать так:
ПодключитьВнешнююКомпоненту(КаталогПрограммы() + "\oscript-simple-gui.dll");

**Comment by ret-Phoenix** [comment]
@alehinsasha Обязательно прошу проверить вариант скачки zip архивом и подключение.

**Comment by alehinsasha** [comment]
@ret-Phoenix как раз закончил проверять) Вместо клонирования - воспользовался вариантом `Download ZIP`, результат - работает.

Действия:
1) `oscript-simple-gui.dll` положил в каталог \OneScript\bin\
2) подключаю так `ПодключитьВнешнююКомпоненту(КаталогПрограммы() + "\oscript-simple-gui.dll");`
3) формирование формы взял из [отсюда](https://github.com/ret-Phoenix/oscript-simple-gui/tree/master/examples)

Спасибо)

**Comment by ret-Phoenix** [comment]
Вот и разобрались)  теперь буду бинарник выкладывать архивом.
Всем спасибо.

**Comment by EvilBeaver** [comment]
По идее, класть компоненту в bin не нужно, начиная с 14 версии 1скрипта

**Comment by ret-Phoenix** [comment]
а куда нужно? мне нравится когда все в одном месте.

**Comment by EvilBeaver** [comment]
@ret-Phoenix в bin лежат компоненты движка, а сама внешняя компонента имеет право находиться где угодно. 1Скрипт должен уметь ее корректно загружать отовсюду.

**Comment by ret-Phoenix** [comment]
Что ВК может лежать где угодно знаю (https://github.com/ret-Phoenix/oscript-simple-gui/issues/12#issuecomment-239830778), есть какие рекомендации по расположению?

Думаю это обсуждение лучше вынести в отдельное место.

**Comment by EvilBeaver** [comment]
@ret-Phoenix рекомендаций нет, складывайте куда угодно )
