### ISSUE TITLE
Сделать packagedef и подключение через Использовать

### ISSUE THREAD

**Issue by EvilBeaver** [ret-Phoenix/oscript-simple-gui#16]
Кажется, что нужно включить пакет в состав библиотеки, чтобы подключалась через Использовать.

**Comment by ret-Phoenix** [comment]
Что мне для этого нужно сделать? (я лишь учусь)))

**Comment by nixel2007** [comment]
@ret-Phoenix что-то такое: https://github.com/oscript-library/cmdline/blob/master/packagedef

**Comment by artbear** [comment]
>Сделать packagedef и подключение через Использовать

@EvilBeaver Расшифруй, что это значит в контексте внешней компоненты.
Пока нам с @ret-Phoenix непонятно :(

**Comment by nixel2007** [comment]
Артур, ну очень просто же.
Не хочу делать "подключить внешнюю компоненту". Хочу `#Использовать
managedInterface` в заголовке.

16 августа 2016 г., 12:41 пользователь Artur Ayukhanov <
notifications@github.com> написал:

**Comment by ret-Phoenix** [comment]
Иначе говоря:
1. Создать класс обертку, в котором кроме как ПодключитьВнешнююКомпоненту() ничего нет
2. Положить обертку в каталог библиотек
так?

**Comment by nixel2007** [comment]
1. да.
2. Почти. еще описание библиотеки сделать (package.def) и залить на opm.

Причем желательно сделать так, чтобы после opm install не надо было регистрировать компоненту. Куда-нибудь ее при установке класть так, чтобы без лишних движений можно было сразу из коробки использовать инструмент.

**Comment by EvilBeaver** [comment]
Можно еще подложить loader в папку пакета, а в нем подключать компоненту

**Comment by dmpas** [comment]
`package-loader.os`
```
Процедура ПриЗагрузкеБиблиотеки(Путь, СтандартнаяОбработка, Отказ)
	
	СтандартнаяОбработка = Ложь;
	ЗагрузитьБиблиотеку(ОбъединитьПути(Путь, "My.dll"));
	
КонецПроцедуры

```

**Comment by nixel2007** [comment]
да, хороший вариант

2016-08-16 13:13 GMT+03:00 Andrei Ovsiankin <notifications@github.com>:

**Comment by ret-Phoenix** [comment]
@EvilBeaver А ведь точно, в том же v8runner это используется.
Мне идея нравится ) ставлю в очередь на реализацию)
