### ISSUE TITLE
Сделать нормальную документацию

### ISSUE THREAD

**Issue by artbear** [ret-Phoenix/oscript-simple-gui#17]
Сейчас дока слишком детализирована.
Нужно инфа о целях продукта, скриншоты/видео, инфа по установке, ссылки на пример использования, короткие примеры использования.

Нужно выделить главное, а детали (например, описание методов) либо перенести ниже по тексту, либо вообще перенести в другой файл.

Длинные примеры использования также можно или перенести ниже, или перенести в другой файл.

**Comment by ret-Phoenix** [comment]
планирую вынести документацию в отдельный файл. так же класть файл для VSCode, благо парсер уже почти готов.

**Comment by artbear** [comment]
ИМХО после #18 лучше не стало
