### ISSUE TITLE
Функции вызова стандартных диалогов

### ISSUE THREAD

**Issue by alexkmbk** [ret-Phoenix/oscript-simple-gui#31]
#38  #39 Хорошо бы в библиотеку добавить функции вызова стандартных диалогов:
- Вопрос
- Предупреждение
- ВвестиЧисло
- ВвестиСтроку

**Comment by alexkmbk** [comment]
Хотя  на мой взгляд эти функции органичнее смотрелись бы в основном движке OneScript, это повысило бы переносимость кода.

**Comment by alexkmbk** [comment]
Поэтому есть предложение перенести этот issue в репозиторий https://github.com/EvilBeaver/OneScript

**Comment by artbear** [comment]
Переноси, это твое право ;)

сб, 10 Сен 2016, 6:06 Alexey Kostromin <notifications@github.com>:

**Comment by nixel2007** [comment]
Из коробки onescript не умеет показывать диалоговые окна.
Данная библиотека - единственная gui-реализация.

**Comment by alexkmbk** [comment]
Можно было бы добавить эти функции в onescript, по крайней мере Вопрос и Предупреждение, остальные две уже есть консольные. Смущает только что на текущий момент проект 1Scdript является консольным и для подключения диалогов, нужно подключать подсистему System.Windows.Forms поскольку для консольных приложений она по умолчанию отключена, приведет ли это к какому-то ухудшению производительности, например к более длительной загрузке - непонятно.

**Comment by dmpas** [comment]
@alexkmbk давай заявку, а там разберёмся. навскидку два варианта: отдельная сборка `oscriptw.exe` как оконное приложение или же добавить возможность во внешних компонентах переопределять `IHostApplication`.

**Comment by alexkmbk** [comment]
Мне кажется как вариант можно было бы добавить эти функции в компоненту oscript-simple-gui, но сделать их глобальными, чтобы сигнатура вызова была такой же как в платформе. 
То есть например так:
```
ПодключитьВнешнююКомпоненту(ОбъединитьПути(КаталогПрограммы(), "oscript-simple-gui.dll"));
Предупреждение("Привет!"); 
```

**Comment by ret-Phoenix** [comment]
Думаю, это будет правильней.
все же изначально OneScript консольное приложение
