### ISSUE TITLE
Невозможно загрузить файл или сборку 

### ISSUE THREAD

**Issue by gambitYP** [ret-Phoenix/oscript-simple-gui#54]
Невозможно загрузить файл или сборку или один из зависимых от них компонентов. Операция не поддерживается. (Исключение из HRESULT: 0x80131515)}   
ПодключитьВнешнююКомпоненту("D:\My\1script\1script\bin\oscript-simple-gui.dll")

ЧЯДНТ?

**Comment by nixel2007** [comment]
каким образом была установлена компонента?

**Comment by nixel2007** [comment]
если из опм, то не надо подключать компоненту вручную. пример  https://github.com/ret-Phoenix/oscript-simple-gui/blob/master/drafts/test.os

**Comment by gambitYP** [comment]
файл releases/gui.zip распаковал в 1script\lib
попытался выполнить пример https://github.com/ret-Phoenix/oscript-simple-gui/blob/master/drafts/test.os

Ошибка:
{Модуль D:\My\1script\lib\gui\package-loader.os / Ошибка в строке: 4 / Внешнее исключение (System.IO.FileLoadException): Невозможно загрузить файл или сборку "file:///D:\My\1script\lib\gui\bin\oscript-gui.dll" или один из зависимых от них компонентов. Операция не поддерживается. (Исключение из HRESULT: 0x80131515)}    
	ПодключитьВнешнююКомпоненту(ОбъединитьПути(Путь, "bin\oscript-gui.dll"));

**Comment by nixel2007** [comment]
В папке releases лежит старый релиз (@ret-phoenix может дропнуть его?).
Актуальную библиотеку надо брать либо с hub.oscript.io либо со страницы релизов на гитхабе. Библиотека ставится либо через `opm install gui` (если с хаба), либо `opm install -f path/to/downloaded/file.ospx` (если ospx скачан самостоятельно)

**Comment by ret-Phoenix** [comment]
сборку брать из релизов github: https://github.com/ret-Phoenix/oscript-simple-gui/releases
Папку удалю, более не актуальна, использовалась изначально, когда OPM был в зародыше.
