### ISSUE TITLE
Разобраться с Enumerator

### ISSUE THREAD

**Issue by ret-Phoenix** [ret-Phoenix/oscript-simple-gui#9]
Код ошибку не выдает, но и ничего не делает:

```
	Группа1 = Форма.Элементы.Добавить("Группа1", "ГруппаФормы", Неопределено);
	Группа1.Вид = ВидыПоляФормы.ОбычнаяГруппа;

	Элемент1 = Форма.Элементы.Добавить("Поле1", "ПолеФормы", Группа1);
	Элемент1 = Форма.Элементы.Добавить("Поле2", "ПолеФормы", Группа1);

	ПодчиненныеЭлементы = Группа1.Элементы;

	Для каждого Элемент Из ПодчиненныеЭлементы Цикл
		Сообщить("Элемент: " + Элемент);
	КонецЦикла;	


```

**Comment by dmpas** [comment]
`SimpleFormElements` должен быть исполнять интерфейс `ICollectionContext`.

Как пример: https://github.com/EvilBeaver/OneScript/blob/03a2d5922575ebc5315047fee1280fbf20a82553/src/ScriptEngine.HostedScript/Library/ArrayImpl.cs#L15

PS в 15 версии там незначительно поменяется.

**Comment by ret-Phoenix** [comment]
Это я реализовал, может в другом проблема...
отлаживаю только через сообщить, не очень удобно и быстро

**Comment by ret-Phoenix** [comment]
Разобрался! оказалось ошибка в классе ГруппаФормы, почему-то список подчиненных пустой. У УправляемаяФорма все работает хорошо )

**Comment by nixel2007** [comment]
@ret-Phoenix а где комменты, привязанные к ишузу? :)

**Comment by ret-Phoenix** [comment]
Моя твоя не понимай )
или ты про коммит в Dev? Там пока нет, как буду в Master - сделаю.

**Comment by nixel2007** [comment]
да, про коммиты :) с содержании #9

**Comment by ret-Phoenix** [comment]
Сейчас идет лавинообразное изменение кода, на каждый чих не создаю issues.
Но надо приучать себя объединять однотипные ошибки и в issues добавлять )
Так что спасибо, что "пнул" )
